/**
 * Strategy Compiler
 * 将参数化策略配置编译为可执行 Python 代码（Freqtrade 兼容）
 */

import { ParameterMetadata, ParameterSpaceContainer } from './parameters';
import { getLogger } from '../../core/logger';

const logger = getLogger('strategy-compiler');

/**
 * 策略配置接口
 */
export interface StrategyConfig {
  name: string;
  description?: string;
  className?: string;  // Python class name, default: CamelCase(name)
  parameters: ParameterSpaceContainer;
  indicators: string[];  // 需要计算的指标列表
  buyCondition: string;  // Python-like boolean expression
  sellCondition: string; // Python-like boolean expression
  timeframe: string;     // e.g., '5m'
  pair?: string;         // optional default pair
  version?: string;      // strategy version
}

/**
 * 编译结果
 */
export interface CompileResult {
  success: boolean;
  code?: string;
  className: string;
  filePath?: string;  // if saved to disk
  errors?: string[];
}

/**
 * 策略编译器
 *
 * 生成兼容 Freqtrade IStrategy 接口的 Python 代码
 */
export class StrategyCompiler {
  private static readonly INDENT = '    '; // 4 spaces

  /**
   * 编译策略配置为 Python 代码
   */
  compile(config: StrategyConfig): CompileResult {
    const errors: string[] = [];

    // 1. 验证配置
    if (!config.name) {
      errors.push('Strategy name is required');
      return { success: false, errors, className: '' };
    }

    const className = config.className || this.toCamelCase(config.name, true);
    const params = config.parameters.getAll();

    // 2. 生成 Python 代码
    try {
      const code = this.generatePythonCode(config, className, params);
      return {
        success: true,
        code,
        className
      };
    } catch (error: any) {
      logger.error('Compilation failed', error);
      return {
        success: false,
        errors: [error.message],
        className
      };
    }
  }

  /**
   * 生成完整的 Python 策略文件
   */
  private generatePythonCode(
    config: StrategyConfig,
    className: string,
    parameters: ParameterMetadata[]
  ): string {
    const lines: string[] = [];

    // Header
    lines.push(`# Generated by OpenClaw Quant Trading`);
    lines.push(`# Strategy: ${config.name}`);
    if (config.description) {
      lines.push(`# Description: ${config.description}`);
    }
    lines.push(`# Generated: ${new Date().toISOString()}`);
    lines.push('');

    // Imports
    lines.push('from datetime import datetime');
    lines.push('from typing import Dict, List, Optional');
    lines.push('import pandas as pd');
    lines.push('import pandas_ta as ta  # fallback if TA-Lib not available');
    lines.push('from freqtrade.strategy import IStrategy, IntParameter, DecimalParameter, BooleanParameter, CategoricalParameter');
    lines.push('');

    // Class definition
    lines.push(`class ${className}(IStrategy):`);
    lines.push(`${StrategyCompiler.INDENT}"""${config.description || config.name}"""`);
    lines.push('');

    // Class attributes
    lines.push(`${StrategyCompiler.INDENT}# Strategy configuration`);
    lines.push(`${StrategyCompiler.INDENT}timeframe = '${config.timeframe}'`);
    if (config.pair) {
      lines.push(`${StrategyCompiler.INDENT}pair = '${config.pair}'`);
    }
    lines.push(`${StrategyCompiler.INDENT}version = '${config.version || '1.0.0'}'`);
    lines.push('');

    // Parameters as class attributes
    if (parameters.length > 0) {
      lines.push(`${StrategyCompiler.INDENT}# Hyperopt parameters`);
      for (const param of parameters) {
        const pyValue = this.pythonValue(param);
        const paramClass = this.parameterClass(param.type);
        lines.push(`${StrategyCompiler.INDENT}${param.name} = ${paramClass}('${param.name}', default=${pyValue})`);
      }
      lines.push('');
    }

    // populate_indicators
    lines.push(`${StrategyCompiler.INDENT}def populate_indicators(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}"""计算技术指标"""`);

    // 参数引用替换
    let buyCondition = config.buyCondition;
    let sellCondition = config.sellCondition;

    for (const param of parameters) {
      const placeholder = `{{${param.name}}}`;
      const pyRef = `self.${param.name}.value`;
      buyCondition = buyCondition.split(placeholder).join(pyRef);
      sellCondition = sellCondition.split(placeholder).join(pyRef);
    }

    // 指标计算代码生成
    if (config.indicators.length > 0) {
      lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}# Calculate indicators`);
      for (const indicator of config.indicators) {
        const code = this.generateIndicatorCode(indicator);
        lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}${code}`);
      }
      lines.push('');
    }

    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}return dataframe`);
    lines.push('');

    // populate_buy_trend
    lines.push(`${StrategyCompiler.INDENT}def populate_buy_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}"""生成买入信号"""`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}dataframe['buy'] = (${this.pyExpr(buyCondition)})`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}return dataframe`);
    lines.push('');

    // populate_sell_trend
    lines.push(`${StrategyCompiler.INDENT}def populate_sell_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}"""生成卖出信号"""`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}dataframe['sell'] = (${this.pyExpr(sellCondition)})`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}return dataframe`);
    lines.push('');

    // optional: custom_stoploss
    lines.push(`${StrategyCompiler.INDENT}def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime, current_rate: float, current_profit: float, after_fill: bool, **kwargs) -> Optional[float]:`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}"""动态止损（可选）"""`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}# TODO: 基于参数实现动态止损`);
    lines.push(`${StrategyCompiler.INDENT}${StrategyCompiler.INDENT}return None`);
    lines.push('');

    return lines.join('\n');
  }

  /**
   * 生成指标计算代码
   */
  private generateIndicatorCode(indicator: string): string {
    // 简单映射，实际需要更复杂的代码生成
    const parts = indicator.toLowerCase().split('_');
    const funcName = parts[0];

    switch (funcName) {
      case 'rsi':
        return `dataframe['rsi'] = ta.rsi(dataframe['close'], length=self.rsi_period)`;
      case 'ema':
        return `dataframe['ema'] = ta.ema(dataframe['close'], length=self.ema_period)`;
      case 'sma':
        return `dataframe['sma'] = ta.sma(dataframe['close'], length=self.sma_period)`;
      case 'atr':
        return `dataframe['atr'] = ta.atr(dataframe['high'], dataframe['low'], dataframe['close'], length=self.atr_period)`;
      case 'macd':
        return `macd = ta.macd(dataframe['close'], fast=self.macd_fast, slow=self.macd_slow, signal=self.macd_signal)\ndataframe['macd'] = macd['MACD']\ndataframe['macd_signal'] = macd['MACDs']\ndataframe['macd_hist'] = macd['MACDh']`;
      case 'bb':
      case 'bbands':
        return `bbands = ta.bbands(dataframe['close'], length=self.bb_length, std=self.bb_std)\ndataframe['bb_upper'] = bbands['BBU']\ndataframe['bb_middle'] = bbands['BBM']\ndataframe['bb_lower'] = bbands['BBL']`;
      default:
        return `# TODO: implement ${indicator}\nraise NotImplementedError('${indicator} not yet supported')`;
    }
  }

  /**
   * 将参数值转换为 Python literal
   */
  private pythonValue(param: ParameterMetadata): any {
    if ((param as any).default !== undefined) {
      return (param as any).default;
    }

    // 基于类型提供默认值
    switch (param.type) {
      case 'integer':
        return 0;
      case 'decimal':
        return 0.0;
      case 'boolean':
        return 'False';
      case 'categorical':
        return `'${(param as any).options[0]}'`;
      default:
        return 'None';
    }
  }

  /**
   * Python 参数类名
   */
  private parameterClass(type: string): string {
    switch (type) {
      case 'integer':
        return 'IntParameter';
      case 'decimal':
        return 'DecimalParameter';
      case 'boolean':
        return 'BooleanParameter';
      case 'categorical':
        return 'CategoricalParameter';
      default:
        return 'IntParameter';
    }
  }

  /**
   * 简单 Python 表达式格式化
   * 将 user condition (e.g., "rsi < 30") 包装为 pandas 布尔表达式
   */
  private pyExpr(expr: string): string {
    // 目前直接返回，假设用户已提供正确的 pandas 表达式
    // 可扩展：变量名自动添加 'dataframe[' 前缀和 ']' 后缀
    return expr;
  }

  /**
   * CamelCase 转换
   */
  private toCamelCase(str: string, pascal: boolean = false): string {
    return str
      .split(/[-_\s]+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }
}

/**
 * 便捷函数：编译策略
 */
export function compileStrategy(config: StrategyConfig): CompileResult {
  const compiler = new StrategyCompiler();
  return compiler.compile(config);
}
